
import { Geist, Geist_Mono, Poppins } from "next/font/google";

import "./globals.css";
import Footer from "./_components/footer/Footer";
import HeaderPage from "./_components/header/Header";

import { cookies } from "next/headers";
import Login from "./_components/authentication/Login";
import Authentication from "./_components/authentication/Authentication";



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});


const poppins = Poppins({
  subsets: ["latin"],
  weight: ['400', '700'], // jitne weight chahiye, array mein daal sakte hain
  variable: "--font-poppins",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  let token = false;
  const cookieStore = await cookies();
  const isLogin = cookieStore.get('token');
  if(isLogin) token= true;

  

  //const isLoggedIn = !!token;

  return (
    <html lang="en">
       <head>
        <link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet" />
      </head>
      <body
        className={`${poppins.variable} antialiased`}
      >

      {/* {!token ? (<div><Authentication /></div>):( */}
      <div className="flex w-full">
      
        <main className="flex-1 w-full">
       
          {children}
         
        </main>
      </div>
      {/* )} */}
      </body>
    </html>
  );
}
